name       : cyrus-sasl
version    : 2.1.26
release    : 8
source     :
    - https://github.com/cyrusimap/cyrus-sasl/releases/download/cyrus-sasl-2.1.26/cyrus-sasl-2.1.26.tar.gz : 8fbc5136512b59bb793657f36fadda6359cae3b08f01fd16b3d406f1345b7bc3
license    : custom
component  : security
summary    : Cyrus Simple Authentication Service Layer (SASL) Library
description: |
    Cyrus Simple Authentication Service Layer (SASL) Library
emul32     : yes
patterns   :
    - devel : [/usr/share/man/man3]
builddeps  :
    - pkgconfig32(krb5)
    - pkgconfig32(openssl)
    - db5-32bit-devel
    - glibc-32bit-devel
    - libgcc-32bit
setup      : |
    %patch -p1 < $pkgfiles/security/cve-2013-4122.patch
    %configure
build      : |
    %make -j1
install    : |
    %make_install -j1
