name       : cyrus-sasl
version    : 2.1.26
release    : 3
source     :
    - ftp://ftp.cyrusimap.org/cyrus-sasl/cyrus-sasl-2.1.26.tar.gz : 8fbc5136512b59bb793657f36fadda6359cae3b08f01fd16b3d406f1345b7bc3
license    : custom
summary    : Cyrus Simple Authentication Service Layer (SASL) Library
description: |
    Cyrus Simple Authentication Service Layer (SASL) Library
builddeps  :
setup      : |
    %patch -p1 < $pkgfiles/security/cve-2013-4122.patch
    %configure
build      : |
    %make
install    : |
    %make_install
