name       : cyrus-sasl
version    : 2.1.27
release    : 10
source     :
    - https://github.com/cyrusimap/cyrus-sasl/releases/download/cyrus-sasl-2.1.27/cyrus-sasl-2.1.27.tar.gz : 26866b1549b00ffd020f188a43c258017fa1c382b3ddadd8201536f72efb05d5
license    : BSD-3-Clause-Attribution
component  : security.library
summary    : Cyrus Simple Authentication Service Layer (SASL) Library
description: |
    Cyrus Simple Authentication Service Layer (SASL) Library
emul32     : yes
patterns   :
    - devel : [/usr/share/man/man3]
builddeps  :
    - pkgconfig32(krb5)
    - db5-32bit-devel
    - glibc-32bit-devel
    - libgcc-32bit
    - openssl-11-32bit-devel
setup      : |
    %configure
build      : |
    %make -j1
install    : |
    %make_install -j1
